### PR TITLE
fix(signature): Ensures that a saved key has 0700 bits on unix

### LINKED ISSUE #115: Bug: create-key should make sure the secret key file mode is 0700
Right now, it doesn't check

### PR DESCRIPTION
**Pull request by thomastaylor312**
Closes #115

### CODE REVIEW

File: src/server/reply.rs [hunk 1]
```diff
@@ -160,8 +160,6 @@ pub fn reply_from_error(
 
 #[cfg(test)]
 mod test {
-    use mime::JSON;
```
Comment (technosophos) [inline src/server/reply.rs:163]: I hate spurious automatic includes from VS Code.

**Review by technosophos — APPROVED** [review]

File: src/invoice/signature.rs [hunk 2]
```diff
@@ -337,7 +339,25 @@ impl SecretKeyFile {
...
-        tokio::fs::write(dest, out).await?;
+        #[cfg(target_family = "unix")]
+        let mut file = OpenOptions::new()
+            .create_new(true)
+            .write(true)
+            .mode(0o700)
+            .open(dest)
+            .await?;
+
+        // TODO(thomastaylor312): Figure out what the proper permissions are on windows (probably
```
Comment (thomastaylor312) [inline src/invoice/signature.rs:350]: Created #176 to track this
